### PR TITLE
Minor tweaks to plotting code and plots

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
@jchodera here are my proposed final figures to send via email to the publisher.  The three PNG files are to be inserted in figures 1 and 2.  The remaining figures and SI will be unchanged.  If you're happy I can send them to publisher.

### CODE REVIEW

**Comment by jchodera** [comment]
Why are we using png files and not vector graphics (pdf)?

**Comment by kyleabeauchamp** [comment]
They don't support vector.

**Comment by jchodera** [comment]
Ah, OK.

Haven't been near a terminal today, but will take a look shortly.  Thanks!

**Comment by kyleabeauchamp** [comment]
Actually i might convert to tif before submission.

**Comment by jchodera** [comment]
Looks good.  If you can change `g / cm ^ 3` to `g / cm$^3$` using the LaTeX feature of matplotlib, that would be awesome, but it isn't super important.

**Comment by kyleabeauchamp** [comment]
OK, updated output format to TIF and used g cm$^-3$.

**Comment by kyleabeauchamp** [comment]
Any last comments before I send these off?

**Pull request merged**
