### PR TITLE
More edits

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
This should implement most of the requested changes in the previous round of edits.

### CODE REVIEW

**Comment by jchodera** [comment]
Looking good!

I just noted a small issue with quotation marks on lines 69-70 of the rendered PDF.

**Comment by jchodera** [comment]
That's here in the diff:
https://github.com/choderalab/LiquidBenchmark/pull/42/files#diff-750ef559d0038ddbd837666a948de896R170

**Comment by jchodera** [comment]
I think we still need to put something in there about your ThermoML Archive retrieval tool once we have that sorted, but maybe we can raise a separate issue about that?  I think that's a key part of the whole message here.

**Comment by kyleabeauchamp** [comment]
Maybe we can email Kenneth to see whether he wants to describe the tool in the manuscript or just on the Github.  I'm willing to go with his needs on this one, as he's in charge of the ThermoML.

**Comment by jchodera** [comment]
> Maybe we can email Kenneth to see whether he wants to describe the tool in the manuscript or just on the Github. I'm willing to go with his needs on this one, as he's in charge of the ThermoML.

Sounds good.  I'll send the email, CCing you.

**Pull request merged**
